package player

import (
	"log"
	"time"

	"bomberman/server/internal/protocol"

	"github.com/gorilla/websocket"
)

const (
	writeWait      = 10 * time.Second
	pongWait       = 60 * time.Second
	pingPeriod     = (pongWait * 9) / 10
	maxMessageSize = 4096 // Increased to comfortably fit long chat text
)

// PlayerMessage wraps a message from a client with the player instance.
type PlayerMessage struct {
	Player *Player
	Msg    protocol.ClientMessage
}

// Player represents a single player in the game.
type Player struct {
	ID       string // Unique identifier provided by frontend or generated by backend
	Position int    // Position 1-4 in the lobby
	Name     string
	Conn     *websocket.Conn
	Send     chan []byte // Channel for sending messages to the player

	ToLobby    chan<- PlayerMessage // Channel to send received messages to the lobby
	Unregister chan<- *Player       // Channel to notify lobby of disconnect
}

// New creates a new Player.
func New(id, name string, conn *websocket.Conn) *Player {
	return &Player{
		ID:   id,
		Name: name,
		Conn: conn,
		Send: make(chan []byte, 256),
	}
}

// ReadPump pumps messages from the websocket connection to the lobby.
func (p *Player) ReadPump() {
	defer func() {
		p.Conn.Close()
		log.Printf("Player %s (%s) ReadPump exiting...", p.Name, p.ID)
		if p.Unregister != nil {
			log.Printf("Player %s (%s) sending Unregister signal to Lobby...", p.Name, p.ID)
			select {
			case p.Unregister <- p:
				log.Printf("Player %s (%s) Unregister signal sent successfully!", p.Name, p.ID)
			case <-time.After(1 * time.Second):
				log.Printf("Player %s (%s) Unregister signal timed out; lobby likely closing.", p.Name, p.ID)
			}
		}
	}()
	p.Conn.SetReadLimit(maxMessageSize)
	p.Conn.SetReadDeadline(time.Now().Add(pongWait))
	p.Conn.SetPongHandler(func(string) error { p.Conn.SetReadDeadline(time.Now().Add(pongWait)); return nil })
	for {
		var msg protocol.ClientMessage
		err := p.Conn.ReadJSON(&msg)
		if err != nil {
			if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway, websocket.CloseAbnormalClosure) {
				log.Printf("error: %v", err)
			}
			break
		}

		// If ToLobby is not set, we can't send.
		if p.ToLobby != nil {
			p.ToLobby <- PlayerMessage{Player: p, Msg: msg}
		}
	}
}

// WritePump pumps messages from the hub to the websocket connection.
func (p *Player) WritePump() {
	ticker := time.NewTicker(pingPeriod)
	defer func() {
		ticker.Stop()
		p.Conn.Close()
		log.Printf("Player %s (%s) WritePump exiting...", p.Name, p.ID)
	}()
	for {
		select {
		case message, ok := <-p.Send:
			p.Conn.SetWriteDeadline(time.Now().Add(writeWait))
			if !ok {
				p.Conn.WriteMessage(websocket.CloseMessage, []byte{})
				return
			}

			w, err := p.Conn.NextWriter(websocket.TextMessage)
			if err != nil {
				return
			}
			w.Write(message)

			if err := w.Close(); err != nil {
				return
			}
		case <-ticker.C:
			p.Conn.SetWriteDeadline(time.Now().Add(writeWait))
			if err := p.Conn.WriteMessage(websocket.PingMessage, nil); err != nil {
				return
			}
		}
	}
}
